services:
  api:
    build:
      context: ./tltk
      dockerfile: Dockerfile
    image: laravel
    volumes:
      - ./tltk:/app
    command: ["php", "artisan", "octane:start", "--host=0.0.0.0", "--port=8080"]
    restart: unless-stopped
    working_dir: /app
    ports:
      - 8000:8080
    depends_on:
      - mysql
  mariadb: # Changed service name for clarity
    image: mariadb:11.3 # Changed to a MariaDB image and version
    container_name: dbmariadb # Changed container name for clarity
    restart: unless-stopped
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD:-password} # Changed to MariaDB specific variable
      - MARIADB_DATABASE=${DB_DATABASE:-app}          # Changed to MariaDB specific variable
    ports:
      - 3306:3306 # Port remains the same as MariaDB also uses 3306 by default
    volumes:
      - mariadb_data:/var/lib/mysql


volumes:
  mariadb_data:
    driver: local
